apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deployment-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:Faisal-Hajari/ai-platform.git
        revision: main
        directories:
          - path: deployment/**
          - path: deployment/*
            exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:Faisal-Hajari/ai-platform.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
