apiVersion: v2
name: nginx-ingress
description: F5 NGINX Ingress Controller
type: application
version: 1.0.0
dependencies:
  - name: nginx-ingress
    version: 2.6.0
    repository: oci://ghcr.io/nginx/charts